[package]
name = "go-press"
version = "0.1.0"
edition = "2024"

[profile.release]
codegen-units = 1
lto = "fat"
strip = true

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking"] }
scraper = "0.23.1"
zip-extract = "0.2.1"
